version: '3.8'

services:
  react-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app # Sync all project files for live updates
      - /usr/src/app/node_modules # Avoid overwriting `node_modules`
    command: ["npm", "start"]
    environment:
      - CHOKIDAR_USEPOLLING=true # Enable hot reloading
